### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by github-2013** [xinshangshangxin/dash-rxjs-6#1]
下载完后直接导入，无法打开我的dash版本是谁4.6.2

**Comment by xinshangshangxin** [comment]
抱歉, 这么晚才看见


把下载的文件放到 `~/Library/Application Support/Dash/DocSets`
然后 退出 `Dash`, 在重启 `Dash`, 打开配置界面, 查看是否存在

![image](https://user-images.githubusercontent.com/8779091/56039060-01d08180-5d66-11e9-8d29-da69018ba79b.png)
